name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --collect-all ultralytics main_tennis.py
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: Tennis-Analysis-Windows
          path: dist/main_tennis.exe
