name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      
      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build EXE
        run: |
          
          # Added --add-data to ensure the model is inside the EXE
          pyinstaller --onefile --windowed --collect-all ultralytics --add-data "yolo26n.pt;." main_gui_tennis.py
          
      - name: Upload Result
        uses: actions/upload-artifact@v4  # Updated to v4 to fix the error
        with:
          name: Tennis-Analysis-Windows
          path: dist/main_gui_tennis.exe  # Must match the .py name used above
